refactor: implement deploying retry

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -111,19 +111,62 @@ jobs:
                   echo "[CD] app-server is in $STATUS state..."
                   continue
                 fi
-                echo "[CD] Deploy Web App"
-                gcloud compute ssh ${{secrets.GCP_SSH_USERNAME}}@app-server \
-                  --zone=$ZONE \
-                  --command="docker pull ${{secrets.DOCKER_HUB_USERNAME}}/mybasket-web-front:latest \
-                  && docker stop front-app || true \
-                  && docker rm front-app || true \
-                  && docker run -d --name front-app -p 80:80 ${{secrets.DOCKER_HUB_USERNAME}}/mybasket-web-front:latest"
-                gcloud compute ssh ${{secrets.GCP_SSH_USERNAME}}@app-server \
-                  --zone=$ZONE \
-                  --command="docker pull ${{secrets.DOCKER_HUB_USERNAME}}/mybasket-web-back:latest \
-                  && docker stop back-app || true \
-                  && docker rm back-app || true \
-                  && docker run -d --name back-app -p 8080:8080 ${{secrets.DOCKER_HUB_USERNAME}}/mybasket-web-back:latest"
+                echo "[CD] Deploy Web front App"
+                # 최대 10번 시도
+                MAX_ATTEMPTS=10
+                ATTEMPT=0
+                
+                while [[ $ATTEMPT -lt $MAX_ATTEMPTS ]]; do
+                    ATTEMPT=$((ATTEMPT + 1))
+                    echo "Attempt $ATTEMPT of $MAX_ATTEMPTS..."
+                
+                    gcloud compute ssh ${{secrets.GCP_SSH_USERNAME}}@app-server \
+                      --zone=$ZONE \
+                      --command="docker pull ${{secrets.DOCKER_HUB_USERNAME}}/mybasket-web-front:latest \
+                      && docker stop front-app || true \
+                      && docker rm front-app || true \
+                      && docker run -d --name front-app -p 80:80 ${{secrets.DOCKER_HUB_USERNAME}}/mybasket-web-front:latest"
+                      
+                    if [[ $? -eq 0 ]]; then
+                        echo "Command succeeded on attempt $ATTEMPT."
+                        break
+                    fi
+                
+                    sleep 1
+                done
+
+                if [ $ATTEMPT -eq MAX_ATTEMPTS ];
+                  echo "[CD] Deploying front-server failed after $MAX_ATTEMPTS attempts."
+                  exit 1
+
+                echo "[CD] Deploy Web back App"
+                # 최대 10번 시도
+                MAX_ATTEMPTS=10
+                ATTEMPT=0
+                
+                while [[ $ATTEMPT -lt $MAX_ATTEMPTS ]]; do
+                    ATTEMPT=$((ATTEMPT + 1))
+                    echo "Attempt $ATTEMPT of $MAX_ATTEMPTS..."
+                
+                    gcloud compute ssh ${{secrets.GCP_SSH_USERNAME}}@app-server \
+                      --zone=$ZONE \
+                      --command="docker pull ${{secrets.DOCKER_HUB_USERNAME}}/mybasket-web-back:latest \
+                      && docker stop back-app || true \
+                      && docker rm back-app || true \
+                      && docker run -d --name back-app -p 8080:8080 ${{secrets.DOCKER_HUB_USERNAME}}/mybasket-web-back:latest"
+                      
+                    if [[ $? -eq 0 ]]; then
+                        echo "Deploying back-server succeeded on attempt $ATTEMPT."
+                        break
+                    fi
+                
+                    sleep 1
+                done
+                
+                if [ $ATTEMPT -eq MAX_ATTEMPTS ];
+                  echo "[CD] Command failed after $MAX_ATTEMPTS attempts."
+                  exit 1
+                
               elif [ $dir == database ]; then
                 ZONE=asia-northeast3-c
                 STATUS=$(gcloud compute instances describe "database-server" --zone=$ZONE --format="get(status)")
@@ -138,12 +181,33 @@ jobs:
                   continue
                 fi
                 echo "[CD] Deploy DB App"
-                gcloud compute ssh ${{secrets.GCP_SSH_USERNAME}}@database-server \
-                  --zone=$ZONE \
-                  --command="docker pull ${{secrets.DOCKER_HUB_USERNAME}}/mybasket-database:latest \
-                  && docker stop db-app || true \
-                  && docker rm db-app || true \
-                  && docker run -d --name db-app -p 3306:3306 ${{secrets.DOCKER_HUB_USERNAME}}/mybasket-database:latest"
+                # 최대 10번 시도
+                MAX_ATTEMPTS=10
+                ATTEMPT=0
+                
+                while [[ $ATTEMPT -lt $MAX_ATTEMPTS ]]; do
+                    ATTEMPT=$((ATTEMPT + 1))
+                    echo "Attempt $ATTEMPT of $MAX_ATTEMPTS..."
+                
+                    gcloud compute ssh ${{secrets.GCP_SSH_USERNAME}}@database-server \
+                      --zone=$ZONE \
+                      --command="docker pull ${{secrets.DOCKER_HUB_USERNAME}}/mybasket-database:latest \
+                      && docker stop db-app || true \
+                      && docker rm db-app || true \
+                      && docker run -d --name db-app -p 3306:3306 ${{secrets.DOCKER_HUB_USERNAME}}/mybasket-database:latest"
+                      
+                    if [[ $? -eq 0 ]]; then
+                        echo "Deploying database-server succeeded on attempt $ATTEMPT."
+                        break
+                    fi
+                
+                    sleep 1
+                done
+                
+                if [ $ATTEMPT -eq MAX_ATTEMPTS ];
+                  echo "[CD] Command failed after $MAX_ATTEMPTS attempts."
+                  exit 1
+                
               elif [ $dir == ml ]; then
                 ZONE=asia-northeast3-b
                 STATUS=$(gcloud compute instances describe "train-server" --zone=$ZONE --format="get(status)")
@@ -158,12 +222,33 @@ jobs:
                   continue
                 fi
                 echo "[CD] Deploy ML App"
-                gcloud compute ssh ${{secrets.GCP_SSH_USERNAME}}@train-server \
-                  --zone=$ZONE \
-                  --command="docker pull ${{secrets.DOCKER_HUB_USERNAME}}/mybasket-ml:latest \
-                  && docker stop ml-app || true \
-                  && docker rm ml-app || true \
-                  && docker run -d --name ml-app -p 8080:8080 ${{secrets.DOCKER_HUB_USERNAME}}/mybasket-ml:latest"
+                # 최대 10번 시도
+                MAX_ATTEMPTS=10
+                ATTEMPT=0
+                
+                while [[ $ATTEMPT -lt $MAX_ATTEMPTS ]]; do
+                    ATTEMPT=$((ATTEMPT + 1))
+                    echo "Attempt $ATTEMPT of $MAX_ATTEMPTS..."
+                
+                    gcloud compute ssh ${{secrets.GCP_SSH_USERNAME}}@train-server \
+                      --zone=$ZONE \
+                      --command="docker pull ${{secrets.DOCKER_HUB_USERNAME}}/mybasket-ml:latest \
+                      && docker stop ml-app || true \
+                      && docker rm ml-app || true \
+                      && docker run -d --name ml-app -p 8080:8080 ${{secrets.DOCKER_HUB_USERNAME}}/mybasket-ml:latest"
+                      
+                    if [[ $? -eq 0 ]]; then
+                        echo "Deploying train-server succeeded on attempt $ATTEMPT."
+                        break
+                    fi
+                
+                    sleep 1
+                done
+                
+                if [ $ATTEMPT -eq MAX_ATTEMPTS ];
+                  echo "[CD] Command failed after $MAX_ATTEMPTS attempts."
+                  exit 1
+                
               elif [ $dir == batch ]; then
                 ZONE=asia-northeast3-c
                 STATUS=$(gcloud compute instances describe "batch-server" --zone=$ZONE --format="get(status)")
@@ -178,12 +263,33 @@ jobs:
                   continue
                 fi
                 echo "[CD] Deploy Batch App"
-                gcloud compute ssh ${{secrets.GCP_SSH_USERNAME}}@batch-server \
-                  --zone=$ZONE \
-                  --command="docker pull ${{secrets.DOCKER_HUB_USERNAME}}/mybasket-batch:latest \
-                  && docker stop batch-app || true \
-                  && docker rm batch-app || true \
-                  && docker run -d --name batch-app -p 8080:8080 ${{secrets.DOCKER_HUB_USERNAME}}/mybasket-batch:latest"
+                
+                # 최대 10번 시도
+                MAX_ATTEMPTS=10
+                ATTEMPT=0
+                
+                while [[ $ATTEMPT -lt $MAX_ATTEMPTS ]]; do
+                    ATTEMPT=$((ATTEMPT + 1))
+                    echo "Attempt $ATTEMPT of $MAX_ATTEMPTS..."
+                
+                    gcloud compute ssh ${{secrets.GCP_SSH_USERNAME}}@batch-server \
+                      --zone=$ZONE \
+                      --command="docker pull ${{secrets.DOCKER_HUB_USERNAME}}/mybasket-batch:latest \
+                      && docker stop batch-app || true \
+                      && docker rm batch-app || true \
+                      && docker run -d --name batch-app -p 8080:8080 ${{secrets.DOCKER_HUB_USERNAME}}/mybasket-batch:latest"
+                    
+                    if [[ $? -eq 0 ]]; then
+                        echo "Deploying batch-server succeeded on attempt $ATTEMPT."
+                        break
+                    fi
+                
+                    sleep 1
+                done
+                
+                if [ $ATTEMPT -eq MAX_ATTEMPTS ];
+                  echo "[CD] Command failed after $MAX_ATTEMPTS attempts."
+                  exit 1
               else
                 echo "[CD] Error: $dir"
               fi
